/*
 @product.name@ JS v@product.version@ (@product.date@)
 Exporting module

 (c) 2010-2014 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(g){var C=g.Chart,x=g.addEvent,D=g.removeEvent,E=HighchartsAdapter.fireEvent,l=g.createElement,u=g.discardElement,z=g.css,n=g.merge,p=g.each,v=g.extend,H=g.splat,I=Math.max,m=document,F=window,J=g.isTouchDevice,K=g.Renderer.prototype.symbols,w=g.getOptions(),q;v(w.lang,{printChart:"Print chart",downloadPNG:"Download PNG image",downloadJPEG:"Download JPEG image",downloadPDF:"Download PDF document",downloadSVG:"Download SVG vector image",contextButtonTitle:"Chart context menu"});w.navigation=
{menuStyle:{border:"1px solid #A0A0A0",background:"#FFFFFF",padding:"5px 0"},menuItemStyle:{padding:"0 10px",background:"none",color:"#303030",fontSize:J?"14px":"11px"},menuItemHoverStyle:{background:"#4572A5",color:"#FFFFFF"},buttonOptions:{symbolFill:"#E0E0E0",symbolSize:14,symbolStroke:"#666",symbolStrokeWidth:3,symbolX:12.5,symbolY:10.5,align:"right",buttonSpacing:3,height:22,theme:{fill:"white",stroke:"none"},verticalAlign:"top",width:24}};w.exporting={type:"image/png",url:"http://export.highcharts.com/",
buttons:{contextButton:{menuClassName:"highcharts-contextmenu",symbol:"menu",_titleKey:"contextButtonTitle",menuItems:[{textKey:"printChart",onclick:function(){this.print()}},{separator:!0},{textKey:"downloadPNG",onclick:function(){this.exportChart()}},{textKey:"downloadJPEG",onclick:function(){this.exportChart({type:"image/jpeg"})}},{textKey:"downloadPDF",onclick:function(){this.exportChart({type:"application/pdf"})}},{textKey:"downloadSVG",onclick:function(){this.exportChart({type:"image/svg+xml"})}}]}}};
g.post=function(b,a,e){var c;b=l("form",n({method:"post",action:b,enctype:"multipart/form-data"},e),{display:"none"},m.body);for(c in a)l("input",{type:"hidden",name:c,value:a[c]},null,b);b.submit();u(b)};v(C.prototype,{sanitizeSVG:function(b){return b.replace(/zIndex="[^"]+"/g,"").replace(/isShadow="[^"]+"/g,"").replace(/symbolName="[^"]+"/g,"").replace(/jQuery[0-9]+="[^"]+"/g,"").replace(/url\([^#]+#/g,"url(#").replace(/<svg /,'<svg xmlns:xlink="http://www.w3.org/1999/xlink" ').replace(/ (NS[0-9]+\:)?href=/g,
" xlink:href=").replace(/\n/," ").replace(/<\/svg>.*?$/,"</svg>").replace(/(fill|stroke)="rgba\(([ 0-9]+,[ 0-9]+,[ 0-9]+),([ 0-9\.]+)\)"/g,'$1="rgb($2)" $1-opacity="$3"').replace(/&nbsp;/g,"\u00a0").replace(/&shy;/g,"\u00ad").replace(/<IMG /g,"<image ").replace(/<(\/?)TITLE>/g,"<$1title>").replace(/height=([^" ]+)/g,'height="$1"').replace(/width=([^" ]+)/g,'width="$1"').replace(/hc-svg-href="([^"]+)">/g,'xlink:href="$1"/>').replace(/ id=([^" >]+)/g,' id="$1"').replace(/class=([^" >]+)/g,'class="$1"').replace(/ transform /g,
" ").replace(/:(path|rect)/g,"$1").replace(/style="([^"]+)"/g,function(a){return a.toLowerCase()})},getChartHTML:function(){return this.container.innerHTML},getSVG:function(b){var a=this,e,c,f,B,h,d=n(a.options,b),L=d.exporting.allowHTML;m.createElementNS||(m.createElementNS=function(a,b){return m.createElement(b)});c=l("div",null,{position:"absolute",top:"-9999em",width:a.chartWidth+"px",height:a.chartHeight+"px"},m.body);f=a.renderTo.style.width;h=a.renderTo.style.height;f=d.exporting.sourceWidth||
d.chart.width||/px$/.test(f)&&parseInt(f,10)||600;h=d.exporting.sourceHeight||d.chart.height||/px$/.test(h)&&parseInt(h,10)||400;v(d.chart,{animation:!1,renderTo:c,forExport:!0,renderer:"SVGRenderer",width:f,height:h});d.exporting.enabled=!1;delete d.data;d.series=[];p(a.series,function(a){B=n(a.options,{animation:!1,enableMouseTracking:!1,showCheckbox:!1,visible:a.visible});B.isInternal||d.series.push(B)});b&&p(["xAxis","yAxis"],function(a){p(H(b[a]),function(b,c){d[a][c]=n(d[a][c],b)})});e=new g.Chart(d,
a.callback);p(["xAxis","yAxis"],function(b){p(a[b],function(a,c){var d=e[b][c],f=a.getExtremes(),h=f.userMin,f=f.userMax;!d||void 0===h&&void 0===f||d.setExtremes(h,f,!0,!1)})});f=e.getChartHTML();d=null;e.destroy();u(c);L&&(c=f.match(/<\/svg>(.*?$)/))&&(c='<foreignObject x="0" y="0" width="200" height="200"><body xmlns="http://www.w3.org/1999/xhtml">'+c[1]+"</body></foreignObject>",f=f.replace("</svg>",c+"</svg>"));f=this.sanitizeSVG(f);return f=f.replace(/(url\(#highcharts-[0-9]+)&quot;/g,"$1").replace(/&quot;/g,
"'")},getSVGForExport:function(b,a){var e=this.options.exporting;return this.getSVG(n({chart:{borderRadius:0}},e.chartOptions,a,{exporting:{sourceWidth:b&&b.sourceWidth||e.sourceWidth,sourceHeight:b&&b.sourceHeight||e.sourceHeight}}))},exportChart:function(b,a){var e=this.getSVGForExport(b,a);b=n(this.options.exporting,b);g.post(b.url,{filename:b.filename||"chart",type:b.type,width:b.width||0,scale:b.scale||2,svg:e},b.formAttributes)},print:function(){var b=this,a=b.container,e=[],c=a.parentNode,
f=m.body,g=f.childNodes;b.isPrinting||(b.isPrinting=!0,E(b,"beforePrint"),p(g,function(a,b){1===a.nodeType&&(e[b]=a.style.display,a.style.display="none")}),f.appendChild(a),F.focus(),F.print(),setTimeout(function(){c.appendChild(a);p(g,function(a,b){1===a.nodeType&&(a.style.display=e[b])});b.isPrinting=!1;E(b,"afterPrint")},1E3))},contextMenu:function(b,a,e,c,f,g,h){var d=this,n=d.options.navigation,G=n.menuItemStyle,r=d.chartWidth,t=d.chartHeight,m="cache-"+b,k=d[m],y=I(f,g),q,A,u,w=function(a){d.pointer.inClass(a.target,
b)||A()};k||(d[m]=k=l("div",{className:b},{position:"absolute",zIndex:1E3,padding:y+"px"},d.container),q=l("div",null,v({MozBoxShadow:"3px 3px 10px #888",WebkitBoxShadow:"3px 3px 10px #888",boxShadow:"3px 3px 10px #888"},n.menuStyle),k),A=function(){z(k,{display:"none"});h&&h.setState(0);d.openMenu=!1},x(k,"mouseleave",function(){u=setTimeout(A,500)}),x(k,"mouseenter",function(){clearTimeout(u)}),x(document,"mouseup",w),x(d,"destroy",function(){D(document,"mouseup",w)}),p(a,function(a){if(a){var b=
a.separator?l("hr",null,null,q):l("div",{onmouseover:function(){z(this,n.menuItemHoverStyle)},onmouseout:function(){z(this,G)},onclick:function(b){b.stopPropagation();A();a.onclick&&a.onclick.apply(d,arguments)},innerHTML:a.text||d.options.lang[a.textKey]},v({cursor:"pointer"},G),q);d.exportDivElements.push(b)}}),d.exportDivElements.push(q,k),d.exportMenuWidth=k.offsetWidth,d.exportMenuHeight=k.offsetHeight);a={display:"block"};e+d.exportMenuWidth>r?a.right=r-e-f-y+"px":a.left=e-y+"px";c+g+d.exportMenuHeight>
t&&"top"!==h.alignOptions.verticalAlign?a.bottom=t-c-y+"px":a.top=c+g-y+"px";z(k,a);d.openMenu=!0},addButton:function(b){var a=this,e=a.renderer,c=n(a.options.navigation.buttonOptions,b),f=c.onclick,m=c.menuItems,h,d,p={stroke:c.symbolStroke,fill:c.symbolFill},l=c.symbolSize||12;a.btnCount||(a.btnCount=0);a.exportDivElements||(a.exportDivElements=[],a.exportSVGElements=[]);if(!1!==c.enabled){var r=c.theme,t=r.states,u=t&&t.hover,t=t&&t.select,k;delete r.states;f?k=function(b){b.stopPropagation();
f.call(a,b)}:m&&(k=function(){a.contextMenu(d.menuClassName,m,d.translateX,d.translateY,d.width,d.height,d);d.setState(2)});c.text&&c.symbol?r.paddingLeft=g.pick(r.paddingLeft,25):c.text||v(r,{width:c.width,height:c.height,padding:0});d=e.button(c.text,0,0,k,r,u,t).attr({title:a.options.lang[c._titleKey],"stroke-linecap":"round"});d.menuClassName=b.menuClassName||"highcharts-menu-"+a.btnCount++;c.symbol&&(h=e.symbol(c.symbol,c.symbolX-l/2,c.symbolY-l/2,l,l).attr(v(p,{"stroke-width":c.symbolStrokeWidth||
1,zIndex:1})).add(d));d.add().align(v(c,{width:d.width,x:g.pick(c.x,q)}),!0,"spacingBox");q+=(d.width+c.buttonSpacing)*("right"===c.align?-1:1);a.exportSVGElements.push(d,h)}},destroyExport:function(b){b=b.target;var a,e;for(a=0;a<b.exportSVGElements.length;a++)if(e=b.exportSVGElements[a])e.onclick=e.ontouchstart=null,b.exportSVGElements[a]=e.destroy();for(a=0;a<b.exportDivElements.length;a++)e=b.exportDivElements[a],D(e,"mouseleave"),b.exportDivElements[a]=e.onmouseout=e.onmouseover=e.ontouchstart=
e.onclick=null,u(e)}});K.menu=function(b,a,e,c){return["M",b,a+2.5,"L",b+e,a+2.5,"M",b,a+c/2+.5,"L",b+e,a+c/2+.5,"M",b,a+c-1.5,"L",b+e,a+c-1.5]};C.prototype.callbacks.push(function(b){var a,e=b.options.exporting,c=e.buttons;q=0;if(!1!==e.enabled){for(a in c)b.addButton(c[a]);x(b,"destroy",b.destroyExport)}})})(Highcharts);
