/*
 Highcharts JS v4.1.9 (2015-10-07)

 (c) 2009-2013 Torstein Hønsi

 License: www.highcharts.com/license
*/
(function(d){function v(c,b,a){var e,f,g=b.options.chart.options3d,h=!1;a?(h=b.inverted,a=b.plotWidth/2,b=b.plotHeight/2):(a=b.plotLeft+b.plotWidth/2,b=b.plotTop+b.plotHeight/2);e=g.depth/2;f=F(g.depth,1)*F(g.viewDistance,0);var l=[],k=a,m=b;b=D*(h?g.beta:-g.beta);var g=D*(h?-g.alpha:g.alpha),n=p(b),w=q(b),r=p(g),B=q(g),t,A,y,u,x,z;d.each(c,function(a){t=(h?a.y:a.x)-k;A=(h?a.x:a.y)-m;y=(a.z||0)-e;u=w*t-n*y;x=-n*r*t-w*r*y+B*A;z=n*B*t+w*B*y+r*A;0<f&&f<Number.POSITIVE_INFINITY&&(u*=f/(z+e+f),x*=f/(z+
e+f));u+=k;x+=m;z+=e;l.push({x:h?x:u,y:h?u:x,z:z})});return l}function E(c){return void 0!==c&&null!==c}function J(c){var b=0,a,e;for(a=0;a<c.length;a++)e=(a+1)%c.length,b+=c[a].x*c[e].y-c[e].x*c[a].y;return b/2}function H(c){var b=0,a;for(a=0;a<c.length;a++)b+=c[a].z;return c.length?b/c.length:0}function C(c,b,a,e,f,g,d,l){var k=[];if(g>f&&g-f>r/2+1E-4)return k=k.concat(C(c,b,a,e,f,f+r/2,d,l)),k=k.concat(C(c,b,a,e,f+r/2,g,d,l));if(g<f&&f-g>r/2+1E-4)return k=k.concat(C(c,b,a,e,f,f-r/2,d,l)),k=k.concat(C(c,
b,a,e,f-r/2,g,d,l));k=g-f;return["C",c+a*q(f)-a*G*k*p(f)+d,b+e*p(f)+e*G*k*q(f)+l,c+a*q(g)+a*G*k*p(g)+d,b+e*p(g)-e*G*k*q(g)+l,c+a*q(g)+d,b+e*p(g)+l]}function K(c){if(this.chart.is3d()){var b=this.chart.options.plotOptions.column.grouping;void 0===b||b||void 0===this.group.zIndex||this.zIndexSet||(this.group.attr({zIndex:10*this.group.zIndex}),this.zIndexSet=!0);var a=this.options,e=this.options.states;this.borderWidth=a.borderWidth=E(a.edgeWidth)?a.edgeWidth:1;d.each(this.data,function(b){null!==b.y&&
(b=b.pointAttr,this.borderColor=d.pick(a.edgeColor,b[""].fill),b[""].stroke=this.borderColor,b.hover.stroke=d.pick(e.hover.edgeColor,this.borderColor),b.select.stroke=d.pick(e.select.edgeColor,this.borderColor))})}c.apply(this,[].slice.call(arguments,1))}var r=Math.PI,D=r/180,p=Math.sin,q=Math.cos,F=d.pick,L=Math.round;d.perspective=v;var G=4*(Math.sqrt(2)-1)/3/(r/2);d.SVGRenderer.prototype.toLinePath=function(c,b){var a=[];d.each(c,function(b){a.push("L",b.x,b.y)});c.length&&(a[0]="M",b&&a.push("Z"));
return a};d.SVGRenderer.prototype.cuboid=function(c){var b=this.g();c=this.cuboidPath(c);b.front=this.path(c[0]).attr({zIndex:c[3],"stroke-linejoin":"round"}).add(b);b.top=this.path(c[1]).attr({zIndex:c[4],"stroke-linejoin":"round"}).add(b);b.side=this.path(c[2]).attr({zIndex:c[5],"stroke-linejoin":"round"}).add(b);b.fillSetter=function(a){var b=d.Color(a).brighten(.1).get(),c=d.Color(a).brighten(-.1).get();this.front.attr({fill:a});this.top.attr({fill:b});this.side.attr({fill:c});this.color=a;return this};
b.opacitySetter=function(a){this.front.attr({opacity:a});this.top.attr({opacity:a});this.side.attr({opacity:a});return this};b.attr=function(a){a.shapeArgs||E(a.x)?(a=this.renderer.cuboidPath(a.shapeArgs||a),this.front.attr({d:a[0],zIndex:a[3]}),this.top.attr({d:a[1],zIndex:a[4]}),this.side.attr({d:a[2],zIndex:a[5]})):d.SVGElement.prototype.attr.call(this,a);return this};b.animate=function(a,b,c){E(a.x)&&E(a.y)?(a=this.renderer.cuboidPath(a),this.front.attr({zIndex:a[3]}).animate({d:a[0]},b,c),this.top.attr({zIndex:a[4]}).animate({d:a[1]},
b,c),this.side.attr({zIndex:a[5]}).animate({d:a[2]},b,c)):a.opacity?(this.front.animate(a,b,c),this.top.animate(a,b,c),this.side.animate(a,b,c)):d.SVGElement.prototype.animate.call(this,a,b,c);return this};b.destroy=function(){this.front.destroy();this.top.destroy();this.side.destroy();return null};b.attr({zIndex:-c[3]});return b};d.SVGRenderer.prototype.cuboidPath=function(c){var b=c.x,a=c.y,e=c.z,f=c.height,g=c.width,h=c.depth,l=d.map,k=[{x:b,y:a,z:e},{x:b+g,y:a,z:e},{x:b+g,y:a+f,z:e},{x:b,y:a+
f,z:e},{x:b,y:a+f,z:e+h},{x:b+g,y:a+f,z:e+h},{x:b+g,y:a,z:e+h},{x:b,y:a,z:e+h}],k=v(k,d.charts[this.chartIndex],c.insidePlotArea),a=function(a,b){a=l(a,function(a){return k[a]});b=l(b,function(a){return k[a]});return 0>J(a)?a:0>J(b)?b:[]};c=a([3,2,1,0],[7,6,5,4]);b=a([1,6,7,0],[4,5,2,3]);a=a([1,2,5,6],[0,7,4,3]);return[this.toLinePath(c,!0),this.toLinePath(b,!0),this.toLinePath(a,!0),H(c),H(b),H(a)]};d.SVGRenderer.prototype.arc3d=function(c){c.alpha*=D;c.beta*=D;var b=this.g(),a=this.arc3dPath(c),
e=b.renderer,f=100*a.zTop;b.shapeArgs=c;b.top=e.path(a.top).setRadialReference(c.center).attr({zIndex:a.zTop}).add(b);b.side1=e.path(a.side2).attr({zIndex:a.zSide1});b.side2=e.path(a.side1).attr({zIndex:a.zSide2});b.inn=e.path(a.inn).attr({zIndex:a.zInn});b.out=e.path(a.out).attr({zIndex:a.zOut});b.fillSetter=function(a){this.color=a;var b=d.Color(a).brighten(-.1).get();this.side1.attr({fill:b});this.side2.attr({fill:b});this.inn.attr({fill:b});this.out.attr({fill:b});this.top.attr({fill:a});return this};
b.translateXSetter=function(a){this.out.attr({translateX:a});this.inn.attr({translateX:a});this.side1.attr({translateX:a});this.side2.attr({translateX:a});this.top.attr({translateX:a})};b.translateYSetter=function(a){this.out.attr({translateY:a});this.inn.attr({translateY:a});this.side1.attr({translateY:a});this.side2.attr({translateY:a});this.top.attr({translateY:a})};b.animate=function(a,b,c){E(a.end)||E(a.start)?(this._shapeArgs=this.shapeArgs,d.SVGElement.prototype.animate.call(this,{_args:a},
{duration:b,start:function(){var a=arguments[0].elem,b=a._shapeArgs;b.fill!==a.color&&a.attr({fill:b.fill})},step:function(){var a=arguments[1],b=a.elem,c=b._shapeArgs,e=a.end,a=a.pos,c=d.merge(c,{x:c.x+(e.x-c.x)*a,y:c.y+(e.y-c.y)*a,r:c.r+(e.r-c.r)*a,innerR:c.innerR+(e.innerR-c.innerR)*a,start:c.start+(e.start-c.start)*a,end:c.end+(e.end-c.end)*a}),e=b.renderer.arc3dPath(c);b.shapeArgs=c;b.top.attr({d:e.top,zIndex:e.zTop});b.inn.attr({d:e.inn,zIndex:e.zInn});b.out.attr({d:e.out,zIndex:e.zOut});b.side1.attr({d:e.side1,
zIndex:e.zSide1});b.side2.attr({d:e.side2,zIndex:e.zSide2})}},c)):d.SVGElement.prototype.animate.call(this,a,b,c);return this};b.destroy=function(){this.top.destroy();this.out.destroy();this.inn.destroy();this.side1.destroy();this.side2.destroy();d.SVGElement.prototype.destroy.call(this)};b.hide=function(){this.top.hide();this.out.hide();this.inn.hide();this.side1.hide();this.side2.hide()};b.show=function(){this.top.show();this.out.show();this.inn.show();this.side1.show();this.side2.show()};b.zIndex=
f;b.attr({zIndex:f});return b};d.SVGRenderer.prototype.arc3dPath=function(c){function b(a){a%=2*r;a>r&&(a=2*r-a);return a}var a=c.x,e=c.y,d=c.start,g=c.end-1E-5,h=c.r,l=c.innerR,k=c.depth,m=c.alpha,n=c.beta,w=q(d),v=p(d);c=q(g);var B=p(g),t=h*q(n),h=h*q(m),A=l*q(n),y=l*q(m),l=k*p(n),u=k*p(m),k=["M",a+t*w,e+h*v],k=k.concat(C(a,e,t,h,d,g,0,0)),k=k.concat(["L",a+A*c,e+y*B]),k=k.concat(C(a,e,A,y,g,d,0,0)),k=k.concat(["Z"]),x=0<n?r/2:0,n=0<m?0:r/2,x=d>-x?d:g>-x?-x:d,z=g<r-n?g:d<r-n?r-n:g,m=["M",a+t*q(x),
e+h*p(x)],m=m.concat(C(a,e,t,h,x,z,0,0));g>r-n&&d<r-n&&(m=m.concat(["L",a+t*q(z)+l,e+h*p(z)+u]),m=m.concat(C(a,e,t,h,z,g,l,u)),m=m.concat(["L",a+t*q(g),e+h*p(g)]),m=m.concat(C(a,e,t,h,g,z,0,0)));m=m.concat(["L",a+t*q(z)+l,e+h*p(z)+u]);m=m.concat(C(a,e,t,h,z,x,l,u));m=m.concat(["Z"]);n=["M",a+A*w,e+y*v];n=n.concat(C(a,e,A,y,d,g,0,0));n=n.concat(["L",a+A*q(g)+l,e+y*p(g)+u]);n=n.concat(C(a,e,A,y,g,d,l,u));n=n.concat(["Z"]);w=["M",a+t*w,e+h*v,"L",a+t*w+l,e+h*v+u,"L",a+A*w+l,e+y*v+u,"L",a+A*w,e+y*v,"Z"];
a=["M",a+t*c,e+h*B,"L",a+t*c+l,e+h*B+u,"L",a+A*c+l,e+y*B+u,"L",a+A*c,e+y*B,"Z"];B=Math.atan2(u,-l);e=Math.abs(g+B);c=Math.abs(d+B);d=Math.abs((d+g)/2+B);e=b(e);c=b(c);d=b(d);d*=1E5;g=1E5*c;e*=1E5;return{top:k,zTop:1E5*r+1,out:m,zOut:Math.max(d,g,e),inn:n,zInn:Math.max(d,g,e),side1:w,zSide1:.99*e,side2:a,zSide2:.99*g}};d.Chart.prototype.is3d=function(){return this.options.chart.options3d&&this.options.chart.options3d.enabled};d.wrap(d.Chart.prototype,"isInsidePlot",function(c){return this.is3d()?!0:
c.apply(this,[].slice.call(arguments,1))});d.getOptions().chart.options3d={enabled:!1,alpha:0,beta:0,depth:100,viewDistance:25,frame:{bottom:{size:1,color:"rgba(255,255,255,0)"},side:{size:1,color:"rgba(255,255,255,0)"},back:{size:1,color:"rgba(255,255,255,0)"}}};d.wrap(d.Chart.prototype,"init",function(c){var b=[].slice.call(arguments,1),a;b[0].chart.options3d&&b[0].chart.options3d.enabled&&(b[0].chart.options3d.alpha=(b[0].chart.options3d.alpha||0)%360,b[0].chart.options3d.beta=(b[0].chart.options3d.beta||
0)%360,a=b[0].plotOptions||{},a=a.pie||{},a.borderColor=d.pick(a.borderColor,void 0));c.apply(this,b)});d.wrap(d.Chart.prototype,"setChartSize",function(c){c.apply(this,[].slice.call(arguments,1));if(this.is3d()){var b=this.inverted,a=this.clipBox,e=this.margin;a[b?"y":"x"]=-(e[3]||0);a[b?"x":"y"]=-(e[0]||0);a[b?"height":"width"]=this.chartWidth+(e[3]||0)+(e[1]||0);a[b?"width":"height"]=this.chartHeight+(e[0]||0)+(e[2]||0)}});d.wrap(d.Chart.prototype,"redraw",function(c){this.is3d()&&(this.isDirtyBox=
!0);c.apply(this,[].slice.call(arguments,1))});d.wrap(d.Chart.prototype,"renderSeries",function(c){var b=this.series.length;if(this.is3d())for(;b--;)c=this.series[b],c.translate(),c.render();else c.call(this)});d.Chart.prototype.retrieveStacks=function(c){var b=this.series,a={},e,f=1;d.each(this.series,function(d){e=F(d.options.stack,c?0:b.length-1-d.index);a[e]?a[e].series.push(d):(a[e]={series:[d],position:f},f++)});a.totalStacks=f+1;return a};d.wrap(d.Axis.prototype,"setOptions",function(c,b){var a;
c.call(this,b);this.chart.is3d()&&(a=this.options,a.tickWidth=d.pick(a.tickWidth,0),a.gridLineWidth=d.pick(a.gridLineWidth,1))});d.wrap(d.Axis.prototype,"render",function(c){c.apply(this,[].slice.call(arguments,1));if(this.chart.is3d()){var b=this.chart,a=b.renderer,e=b.options.chart.options3d,d=e.frame,g=d.bottom,h=d.back,d=d.side,l=e.depth,k=this.height,m=this.width,n=this.left,w=this.top;this.isZAxis||(this.horiz?(h={x:n,y:w+(b.xAxis[0].opposite?-g.size:k),z:0,width:m,height:g.size,depth:l,insidePlotArea:!1},
this.bottomFrame?this.bottomFrame.animate(h):this.bottomFrame=a.cuboid(h).attr({fill:g.color,zIndex:b.yAxis[0].reversed&&0<e.alpha?4:-1}).css({stroke:g.color}).add()):(e={x:n+(b.yAxis[0].opposite?0:-d.size),y:w+(b.xAxis[0].opposite?-g.size:0),z:l,width:m+d.size,height:k+g.size,depth:h.size,insidePlotArea:!1},this.backFrame?this.backFrame.animate(e):this.backFrame=a.cuboid(e).attr({fill:h.color,zIndex:-3}).css({stroke:h.color}).add(),b={x:n+(b.yAxis[0].opposite?m:-d.size),y:w+(b.xAxis[0].opposite?
-g.size:0),z:0,width:d.size,height:k+g.size,depth:l,insidePlotArea:!1},this.sideFrame?this.sideFrame.animate(b):this.sideFrame=a.cuboid(b).attr({fill:d.color,zIndex:-2}).css({stroke:d.color}).add()))}});d.wrap(d.Axis.prototype,"getPlotLinePath",function(c){var b=c.apply(this,[].slice.call(arguments,1));if(!this.chart.is3d()||null===b)return b;var a=this.chart.options.chart.options3d,a=this.isZAxis?this.chart.plotWidth:a.depth,d=this.opposite;this.horiz&&(d=!d);b=[this.swapZ({x:b[1],y:b[2],z:d?a:0}),
this.swapZ({x:b[1],y:b[2],z:a}),this.swapZ({x:b[4],y:b[5],z:a}),this.swapZ({x:b[4],y:b[5],z:d?0:a})];b=v(b,this.chart,!1);return b=this.chart.renderer.toLinePath(b,!1)});d.wrap(d.Axis.prototype,"getLinePath",function(c){return this.chart.is3d()?[]:c.apply(this,[].slice.call(arguments,1))});d.wrap(d.Axis.prototype,"getPlotBandPath",function(c){if(this.chart.is3d()){var b=arguments,a=b[1],b=this.getPlotLinePath(b[2]);(a=this.getPlotLinePath(a))&&b?a.push("L",b[10],b[11],"L",b[7],b[8],"L",b[4],b[5],
"L",b[1],b[2]):a=null;return a}return c.apply(this,[].slice.call(arguments,1))});d.wrap(d.Tick.prototype,"getMarkPath",function(c){var b=c.apply(this,[].slice.call(arguments,1));if(!this.axis.chart.is3d())return b;b=[this.axis.swapZ({x:b[1],y:b[2],z:0}),this.axis.swapZ({x:b[4],y:b[5],z:0})];b=v(b,this.axis.chart,!1);return b=["M",b[0].x,b[0].y,"L",b[1].x,b[1].y]});d.wrap(d.Tick.prototype,"getLabelPosition",function(c){var b=c.apply(this,[].slice.call(arguments,1));if(!this.axis.chart.is3d())return b;
var a=v([this.axis.swapZ({x:b.x,y:b.y,z:0})],this.axis.chart,!1)[0];a.x-=!this.axis.horiz&&this.axis.opposite?this.axis.transA:0;a.old=b;return a});d.wrap(d.Tick.prototype,"handleOverflow",function(c,b){this.axis.chart.is3d()&&(b=b.old);return c.call(this,b)});d.wrap(d.Axis.prototype,"getTitlePosition",function(c){var b=c.apply(this,[].slice.call(arguments,1));return this.chart.is3d()?b=v([this.swapZ({x:b.x,y:b.y,z:0})],this.chart,!1)[0]:b});d.wrap(d.Axis.prototype,"drawCrosshair",function(c){var b=
arguments;this.chart.is3d()&&b[2]&&(b[2]={plotX:b[2].plotXold||b[2].plotX,plotY:b[2].plotYold||b[2].plotY});c.apply(this,[].slice.call(b,1))});d.Axis.prototype.swapZ=function(c,b){if(this.isZAxis){var a=b?0:this.chart.plotLeft,d=this.chart;return{x:a+(d.yAxis[0].opposite?c.z:d.xAxis[0].width-c.z),y:c.y,z:c.x-a}}return c};var I=d.ZAxis=function(){this.isZAxis=!0;this.init.apply(this,arguments)};d.extend(I.prototype,d.Axis.prototype);d.extend(I.prototype,{setOptions:function(c){c=d.merge({offset:0,
lineWidth:0},c);d.Axis.prototype.setOptions.call(this,c);this.coll="zAxis"},setAxisSize:function(){d.Axis.prototype.setAxisSize.call(this);this.width=this.len=this.chart.options.chart.options3d.depth;this.right=this.chart.chartWidth-this.width-this.left},getSeriesExtremes:function(){var c=this,b=c.chart;c.hasVisibleSeries=!1;c.dataMin=c.dataMax=c.ignoreMinPadding=c.ignoreMaxPadding=null;c.buildStacks&&c.buildStacks();d.each(c.series,function(a){if(a.visible||!b.options.chart.ignoreHiddenSeries)c.hasVisibleSeries=
!0,a=a.zData,a.length&&(c.dataMin=Math.min(F(c.dataMin,a[0]),Math.min.apply(null,a)),c.dataMax=Math.max(F(c.dataMax,a[0]),Math.max.apply(null,a)))})}});d.wrap(d.Chart.prototype,"getAxes",function(c){var b=this,a=this.options,a=a.zAxis=d.splat(a.zAxis||{});c.call(this);b.is3d()&&(this.zAxis=[],d.each(a,function(a,c){a.index=c;a.isX=!0;(new I(b,a)).setScale()}))});d.wrap(d.seriesTypes.column.prototype,"translate",function(c){c.apply(this,[].slice.call(arguments,1));if(this.chart.is3d()){var b=this.chart,
a=this.options,e=a.depth||25,f=(a.stacking?a.stack||0:this._i)*(e+(a.groupZPadding||1));!1!==a.grouping&&(f=0);f+=a.groupZPadding||1;d.each(this.data,function(a){if(null!==a.y){var c=a.shapeArgs,d=a.tooltipPos;a.shapeType="cuboid";c.z=f;c.depth=e;c.insidePlotArea=!0;d=v([{x:d[0],y:d[1],z:f}],b,!1)[0];a.tooltipPos=[d.x,d.y]}});this.z=f}});d.wrap(d.seriesTypes.column.prototype,"animate",function(c){if(this.chart.is3d()){var b=arguments[1],a=this.yAxis,e=this,f=this.yAxis.reversed;d.svg&&(b?d.each(e.data,
function(b){null!==b.y&&(b.height=b.shapeArgs.height,b.shapey=b.shapeArgs.y,b.shapeArgs.height=1,f||(b.shapeArgs.y=b.stackY?b.plotY+a.translate(b.stackY):b.plotY+(b.negative?-b.height:b.height)))}):(d.each(e.data,function(a){null!==a.y&&(a.shapeArgs.height=a.height,a.shapeArgs.y=a.shapey,a.graphic&&a.graphic.animate(a.shapeArgs,e.options.animation))}),this.drawDataLabels(),e.animate=null))}else c.apply(this,[].slice.call(arguments,1))});d.wrap(d.seriesTypes.column.prototype,"init",function(c){c.apply(this,
[].slice.call(arguments,1));if(this.chart.is3d()){var b=this.options,a=b.grouping,d=b.stacking,f=0;if(void 0===a||a){a=this.chart.retrieveStacks(d);d=b.stack||0;for(f=0;f<a[d].series.length&&a[d].series[f]!==this;f++);f=10*a.totalStacks-10*(a.totalStacks-a[d].position)-f}b.zIndex=f}});d.wrap(d.Series.prototype,"alignDataLabel",function(c){if(this.chart.is3d()&&("column"===this.type||"columnrange"===this.type)){var b=arguments[4],a={x:b.x,y:b.y,z:this.z},a=v([a],this.chart,!0)[0];b.x=a.x;b.y=a.y}c.apply(this,
[].slice.call(arguments,1))});d.seriesTypes.columnrange&&d.wrap(d.seriesTypes.columnrange.prototype,"drawPoints",K);d.wrap(d.seriesTypes.column.prototype,"drawPoints",K);d.wrap(d.seriesTypes.pie.prototype,"translate",function(c){c.apply(this,[].slice.call(arguments,1));if(this.chart.is3d()){var b=this,a=b.chart,e=b.options,f=e.depth||0,g=a.options.chart.options3d,h={x:a.plotWidth/2,y:a.plotHeight/2,z:g.depth},l=g.alpha,k=g.beta,m=e.stacking?(e.stack||0)*f:b._i*f,m=m+f/2;!1!==e.grouping&&(m=0);d.each(b.data,
function(a){var c=a.shapeArgs;a.shapeType="arc3d";c.z=m;c.depth=.75*f;c.origin=h;c.alpha=l;c.beta=k;c.center=b.center;c=(c.end+c.start)/2;a.slicedTranslation={translateX:L(q(c)*e.slicedOffset*q(l*D)),translateY:L(p(c)*e.slicedOffset*q(l*D))}})}});d.wrap(d.seriesTypes.pie.prototype.pointClass.prototype,"haloPath",function(c){var b=arguments;return this.series.chart.is3d()?[]:c.call(this,b[1])});d.wrap(d.seriesTypes.pie.prototype,"drawPoints",function(c){var b=this.group,a=this.options,e=a.states;this.chart.is3d()&&
(this.borderWidth=a.borderWidth=a.edgeWidth||1,this.borderColor=a.edgeColor=d.pick(a.edgeColor,a.borderColor,void 0),e.hover.borderColor=d.pick(e.hover.edgeColor,this.borderColor),e.hover.borderWidth=d.pick(e.hover.edgeWidth,this.borderWidth),e.select.borderColor=d.pick(e.select.edgeColor,this.borderColor),e.select.borderWidth=d.pick(e.select.edgeWidth,this.borderWidth),d.each(this.data,function(a){var b=a.pointAttr;b[""].stroke=a.series.borderColor||a.color;b[""]["stroke-width"]=a.series.borderWidth;
b.hover.stroke=e.hover.borderColor;b.hover["stroke-width"]=e.hover.borderWidth;b.select.stroke=e.select.borderColor;b.select["stroke-width"]=e.select.borderWidth}));c.apply(this,[].slice.call(arguments,1));this.chart.is3d()&&d.each(this.points,function(a){var c=a.graphic;c.out.add(b);c.inn.add(b);c.side1.add(b);c.side2.add(b);c[a.y?"show":"hide"]()})});d.wrap(d.seriesTypes.pie.prototype,"drawDataLabels",function(c){if(this.chart.is3d()){var b=this;d.each(b.data,function(a){var c=a.shapeArgs,d=c.r,
g=c.depth,h=(c.alpha||b.chart.options.chart.options3d.alpha)*D,c=(c.start+c.end)/2;a=a.labelPos;a[1]+=-d*(1-q(h))*p(c)+(0<p(c)?p(h)*g:0);a[3]+=-d*(1-q(h))*p(c)+(0<p(c)?p(h)*g:0);a[5]+=-d*(1-q(h))*p(c)+(0<p(c)?p(h)*g:0)})}c.apply(this,[].slice.call(arguments,1))});d.wrap(d.seriesTypes.pie.prototype,"addPoint",function(c){c.apply(this,[].slice.call(arguments,1));this.chart.is3d()&&this.update(this.userOptions,!0)});d.wrap(d.seriesTypes.pie.prototype,"animate",function(c){if(this.chart.is3d()){var b=
arguments[1],a=this.options.animation,e=this.center,f=this.group,g=this.markerGroup;d.svg&&(!0===a&&(a={}),b?(f.oldtranslateX=f.translateX,f.oldtranslateY=f.translateY,b={translateX:e[0],translateY:e[1],scaleX:.001,scaleY:.001},f.attr(b),g&&(g.attrSetters=f.attrSetters,g.attr(b))):(b={translateX:f.oldtranslateX,translateY:f.oldtranslateY,scaleX:1,scaleY:1},f.animate(b,a),g&&g.animate(b,a),this.animate=null))}else c.apply(this,[].slice.call(arguments,1))});d.wrap(d.seriesTypes.scatter.prototype,"translate",
function(c){c.apply(this,[].slice.call(arguments,1));if(this.chart.is3d()){var b=this.chart,a=d.pick(this.zAxis,b.options.zAxis[0]),e=[],f,g,h;for(h=0;h<this.data.length;h++)f=this.data[h],g=a.isLog&&a.val2lin?a.val2lin(f.z):f.z,f.plotZ=a.translate(g),f.isInside=f.isInside?g>=a.min&&g<=a.max:!1,e.push({x:f.plotX,y:f.plotY,z:f.plotZ});b=v(e,b,!0);for(h=0;h<this.data.length;h++)f=this.data[h],a=b[h],f.plotXold=f.plotX,f.plotYold=f.plotY,f.plotX=a.x,f.plotY=a.y,f.plotZ=a.z}});d.wrap(d.seriesTypes.scatter.prototype,
"init",function(c,b,a){b.is3d()&&(this.axisTypes=["xAxis","yAxis","zAxis"],this.pointArrayMap=["x","y","z"],this.parallelArrays=["x","y","z"]);c=c.apply(this,[b,a]);this.chart.is3d()&&(this.tooltipOptions.pointFormat=this.userOptions.tooltip?this.userOptions.tooltip.pointFormat||"x: <b>{point.x}</b><br/>y: <b>{point.y}</b><br/>z: <b>{point.z}</b><br/>":"x: <b>{point.x}</b><br/>y: <b>{point.y}</b><br/>z: <b>{point.z}</b><br/>");return c});d.VMLRenderer&&(d.setOptions({animate:!1}),d.VMLRenderer.prototype.cuboid=
d.SVGRenderer.prototype.cuboid,d.VMLRenderer.prototype.cuboidPath=d.SVGRenderer.prototype.cuboidPath,d.VMLRenderer.prototype.toLinePath=d.SVGRenderer.prototype.toLinePath,d.VMLRenderer.prototype.createElement3D=d.SVGRenderer.prototype.createElement3D,d.VMLRenderer.prototype.arc3d=function(c){c=d.SVGRenderer.prototype.arc3d.call(this,c);c.css({zIndex:c.zIndex});return c},d.VMLRenderer.prototype.arc3dPath=d.SVGRenderer.prototype.arc3dPath,d.wrap(d.Axis.prototype,"render",function(c){c.apply(this,[].slice.call(arguments,
1));this.sideFrame&&(this.sideFrame.css({zIndex:0}),this.sideFrame.front.attr({fill:this.sideFrame.color}));this.bottomFrame&&(this.bottomFrame.css({zIndex:1}),this.bottomFrame.front.attr({fill:this.bottomFrame.color}));this.backFrame&&(this.backFrame.css({zIndex:0}),this.backFrame.front.attr({fill:this.backFrame.color}))}))})(Highcharts);
