/*
 Highcharts JS v4.1.9 (2015-10-07)

 (c) 2009-2014 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(q,K){function P(a,b,c){this.init.call(this,a,b,c)}var U=q.arrayMin,V=q.arrayMax,x=q.each,M=q.extend,y=q.merge,W=q.map,r=q.pick,F=q.pInt,t=q.getOptions().plotOptions,k=q.seriesTypes,v=q.extendClass,Q=q.splat,w=q.wrap,R=q.Axis,D=q.Tick,N=q.Point,X=q.Pointer,Y=q.CenteredSeriesMixin,E=q.TrackerMixin,A=q.Series,C=Math,I=C.round,G=C.floor,S=C.max,Z=q.Color,z=function(){};M(P.prototype,{init:function(a,b,c){var d=this,e=d.defaultOptions;d.chart=b;d.options=a=y(e,b.angular?{background:{}}:void 0,
a);(a=a.background)&&x([].concat(Q(a)).reverse(),function(a){var b=a.backgroundColor,m=c.userOptions;a=y(d.defaultBackgroundOptions,a);b&&(a.backgroundColor=b);a.color=a.backgroundColor;c.options.plotBands.unshift(a);m.plotBands=m.plotBands||[];m.plotBands!==c.options.plotBands&&m.plotBands.unshift(a)})},defaultOptions:{center:["50%","50%"],size:"85%",startAngle:0},defaultBackgroundOptions:{shape:"circle",borderWidth:1,borderColor:"silver",backgroundColor:{linearGradient:{x1:0,y1:0,x2:0,y2:1},stops:[[0,
"#FFF"],[1,"#DDD"]]},from:-Number.MAX_VALUE,innerRadius:0,to:Number.MAX_VALUE,outerRadius:"105%"}});var L=R.prototype,D=D.prototype,aa={getOffset:z,redraw:function(){this.isDirty=!1},render:function(){this.isDirty=!1},setScale:z,setCategories:z,setTitle:z},T={isRadial:!0,defaultRadialGaugeOptions:{labels:{align:"center",x:0,y:null},minorGridLineWidth:0,minorTickInterval:"auto",minorTickLength:10,minorTickPosition:"inside",minorTickWidth:1,tickLength:10,tickPosition:"inside",tickWidth:2,title:{rotation:0},
zIndex:2},defaultRadialXOptions:{gridLineWidth:1,labels:{align:null,distance:15,x:0,y:null},maxPadding:0,minPadding:0,showLastLabel:!1,tickLength:0},defaultRadialYOptions:{gridLineInterpolation:"circle",labels:{align:"right",x:-3,y:-2},showLastLabel:!1,title:{x:4,text:null,rotation:90}},setOptions:function(a){a=this.options=y(this.defaultOptions,this.defaultRadialOptions,a);a.plotBands||(a.plotBands=[])},getOffset:function(){L.getOffset.call(this);this.chart.axisOffset[this.side]=0;this.center=this.pane.center=
Y.getCenter.call(this.pane)},getLinePath:function(a,b){var c=this.center;b=r(b,c[2]/2-this.offset);return this.chart.renderer.symbols.arc(this.left+c[0],this.top+c[1],b,b,{start:this.startAngleRad,end:this.endAngleRad,open:!0,innerR:0})},setAxisTranslation:function(){L.setAxisTranslation.call(this);this.center&&(this.transA=this.isCircular?(this.endAngleRad-this.startAngleRad)/(this.max-this.min||1):this.center[2]/2/(this.max-this.min||1),this.minPixelPadding=this.isXAxis?this.transA*this.minPointOffset:
0)},beforeSetTickPositions:function(){this.autoConnect&&(this.max+=this.categories&&1||this.pointRange||this.closestPointRange||0)},setAxisSize:function(){L.setAxisSize.call(this);this.isRadial&&(this.center=this.pane.center=q.CenteredSeriesMixin.getCenter.call(this.pane),this.isCircular&&(this.sector=this.endAngleRad-this.startAngleRad),this.len=this.width=this.height=this.center[2]*r(this.sector,1)/2)},getPosition:function(a,b){return this.postTranslate(this.isCircular?this.translate(a):0,r(this.isCircular?
b:this.translate(a),this.center[2]/2)-this.offset)},postTranslate:function(a,b){var c=this.chart,d=this.center;a=this.startAngleRad+a;return{x:c.plotLeft+d[0]+Math.cos(a)*b,y:c.plotTop+d[1]+Math.sin(a)*b}},getPlotBandPath:function(a,b,c){var d=this.center,e=this.startAngleRad,f=d[2]/2,h=[r(c.outerRadius,"100%"),c.innerRadius,r(c.thickness,10)],m=/%$/,g,l=this.isCircular;"polygon"===this.options.gridLineInterpolation?d=this.getPlotLinePath(a).concat(this.getPlotLinePath(b,!0)):(a=Math.max(a,this.min),
b=Math.min(b,this.max),l||(h[0]=this.translate(a),h[1]=this.translate(b)),h=W(h,function(a){m.test(a)&&(a=F(a,10)*f/100);return a}),"circle"!==c.shape&&l?(a=e+this.translate(a),b=e+this.translate(b)):(a=-Math.PI/2,b=1.5*Math.PI,g=!0),d=this.chart.renderer.symbols.arc(this.left+d[0],this.top+d[1],h[0],h[0],{start:Math.min(a,b),end:Math.max(a,b),innerR:r(h[1],h[0]-h[2]),open:g}));return d},getPlotLinePath:function(a,b){var c=this,d=c.center,e=c.chart,f=c.getPosition(a),h,m,g;c.isCircular?g=["M",d[0]+
e.plotLeft,d[1]+e.plotTop,"L",f.x,f.y]:"circle"===c.options.gridLineInterpolation?(a=c.translate(a))&&(g=c.getLinePath(0,a)):(x(e.xAxis,function(a){a.pane===c.pane&&(h=a)}),g=[],a=c.translate(a),d=h.tickPositions,h.autoConnect&&(d=d.concat([d[0]])),b&&(d=[].concat(d).reverse()),x(d,function(f,b){m=h.getPosition(f,a);g.push(b?"L":"M",m.x,m.y)}));return g},getTitlePosition:function(){var a=this.center,b=this.chart,c=this.options.title;return{x:b.plotLeft+a[0]+(c.x||0),y:b.plotTop+a[1]-{high:.5,middle:.25,
low:0}[c.align]*a[2]+(c.y||0)}}};w(L,"init",function(a,b,c){var d=b.angular,e=b.polar,f=c.isX,h=d&&f,m,g;g=b.options;var l=c.pane||0;if(d){if(M(this,h?aa:T),m=!f)this.defaultRadialOptions=this.defaultRadialGaugeOptions}else e&&(M(this,T),this.defaultRadialOptions=(m=f)?this.defaultRadialXOptions:y(this.defaultYAxisOptions,this.defaultRadialYOptions));a.call(this,b,c);h||!d&&!e||(a=this.options,b.panes||(b.panes=[]),this.pane=l=b.panes[l]=b.panes[l]||new P(Q(g.pane)[l],b,this),l=l.options,b.inverted=
!1,g.chart.zoomType=null,this.startAngleRad=b=(l.startAngle-90)*Math.PI/180,this.endAngleRad=g=(r(l.endAngle,l.startAngle+360)-90)*Math.PI/180,this.offset=a.offset||0,(this.isCircular=m)&&c.max===K&&g-b===2*Math.PI&&(this.autoConnect=!0))});w(D,"getPosition",function(a,b,c,d,e){var f=this.axis;return f.getPosition?f.getPosition(c):a.call(this,b,c,d,e)});w(D,"getLabelPosition",function(a,b,c,d,e,f,h,m,g){var l=this.axis,p=f.y,n=20,k=f.align,B=(l.translate(this.pos)+l.startAngleRad+Math.PI/2)/Math.PI*
180%360;l.isRadial?(a=l.getPosition(this.pos,l.center[2]/2+r(f.distance,-25)),"auto"===f.rotation?d.attr({rotation:B}):null===p&&(p=l.chart.renderer.fontMetrics(d.styles.fontSize).b-d.getBBox().height/2),null===k&&(l.isCircular?(this.label.getBBox().width>l.len*l.tickInterval/(l.max-l.min)&&(n=0),k=B>n&&B<180-n?"left":B>180+n&&B<360-n?"right":"center"):k="center",d.attr({align:k})),a.x+=f.x,a.y+=p):a=a.call(this,b,c,d,e,f,h,m,g);return a});w(D,"getMarkPath",function(a,b,c,d,e,f,h){var m=this.axis;
m.isRadial?(a=m.getPosition(this.pos,m.center[2]/2+d),b=["M",b,c,"L",a.x,a.y]):b=a.call(this,b,c,d,e,f,h);return b});t.arearange=y(t.area,{lineWidth:1,marker:null,threshold:null,tooltip:{pointFormat:'<span style="color:{series.color}">\u25cf</span> {series.name}: <b>{point.low}</b> - <b>{point.high}</b><br/>'},trackByArea:!0,dataLabels:{align:null,verticalAlign:null,xLow:0,xHigh:0,yLow:0,yHigh:0},states:{hover:{halo:!1}}});k.arearange=v(k.area,{type:"arearange",pointArrayMap:["low","high"],dataLabelCollections:["dataLabel",
"dataLabelUpper"],toYData:function(a){return[a.low,a.high]},pointValKey:"low",deferTranslatePolar:!0,highToXY:function(a){var b=this.chart,c=this.xAxis.postTranslate(a.rectPlotX,this.yAxis.len-a.plotHigh);a.plotHighX=c.x-b.plotLeft;a.plotHigh=c.y-b.plotTop},getSegments:function(){var a=this;x(a.points,function(b){a.options.connectNulls||null!==b.low&&null!==b.high?null===b.low&&null!==b.high&&(b.y=b.high):b.y=null});A.prototype.getSegments.call(this)},translate:function(){var a=this,b=a.yAxis;k.area.prototype.translate.apply(a);
x(a.points,function(a){var d=a.low,e=a.high,f=a.plotY;null===e&&null===d?a.y=null:null===d?(a.plotLow=a.plotY=null,a.plotHigh=b.translate(e,0,1,0,1)):null===e?(a.plotLow=f,a.plotHigh=null):(a.plotLow=f,a.plotHigh=b.translate(e,0,1,0,1))});this.chart.polar&&x(this.points,function(b){a.highToXY(b)})},getSegmentPath:function(a){var b,c=[],d=a.length,e=A.prototype.getSegmentPath,f,h;h=this.options;var m=h.step;for(b=HighchartsAdapter.grep(a,function(a){return null!==a.plotLow});d--;)f=a[d],null!==f.plotHigh&&
c.push({plotX:f.plotHighX||f.plotX,plotY:f.plotHigh});a=e.call(this,b);m&&(!0===m&&(m="left"),h.step={left:"right",center:"center",right:"left"}[m]);c=e.call(this,c);h.step=m;h=[].concat(a,c);this.chart.polar||(c[0]="L");this.areaPath=this.areaPath.concat(a,c);return h},drawDataLabels:function(){var a=this.data,b=a.length,c,d=[],e=A.prototype,f=this.options.dataLabels,h=f.align,m=f.inside,g,l,p=this.chart.inverted;if(f.enabled||this._hasPointLabels){for(c=b;c--;)if(g=a[c])l=m?g.plotHigh<g.plotLow:
g.plotHigh>g.plotLow,g.y=g.high,g._plotY=g.plotY,g.plotY=g.plotHigh,d[c]=g.dataLabel,g.dataLabel=g.dataLabelUpper,g.below=l,p?(h||(f.align=l?"right":"left"),f.x=f.xHigh):f.y=f.yHigh;e.drawDataLabels&&e.drawDataLabels.apply(this,arguments);for(c=b;c--;)if(g=a[c])l=m?g.plotHigh<g.plotLow:g.plotHigh>g.plotLow,g.dataLabelUpper=g.dataLabel,g.dataLabel=d[c],g.y=g.low,g.plotY=g._plotY,g.below=!l,p?(h||(f.align=l?"left":"right"),f.x=f.xLow):f.y=f.yLow;e.drawDataLabels&&e.drawDataLabels.apply(this,arguments)}f.align=
h},alignDataLabel:function(){k.column.prototype.alignDataLabel.apply(this,arguments)},setStackedPoints:z,getSymbol:z,drawPoints:z});t.areasplinerange=y(t.arearange);k.areasplinerange=v(k.arearange,{type:"areasplinerange",getPointSpline:k.spline.prototype.getPointSpline});(function(){var a=k.column.prototype;t.columnrange=y(t.column,t.arearange,{lineWidth:1,pointRange:null});k.columnrange=v(k.arearange,{type:"columnrange",translate:function(){var b=this,c=b.yAxis,d;a.translate.apply(b);x(b.points,
function(a){var f=a.shapeArgs,h=b.options.minPointLength,m;a.tooltipPos=null;a.plotHigh=d=c.translate(a.high,0,1,0,1);a.plotLow=a.plotY;m=d;a=a.plotY-d;Math.abs(a)<h?(h-=a,a+=h,m-=h/2):0>a&&(a*=-1,m-=a);f.height=a;f.y=m})},directTouch:!0,trackerGroups:["group","dataLabelsGroup"],drawGraph:z,crispCol:a.crispCol,pointAttrToOptions:a.pointAttrToOptions,drawPoints:a.drawPoints,drawTracker:a.drawTracker,animate:a.animate,getColumnMetrics:a.getColumnMetrics})})();t.gauge=y(t.line,{dataLabels:{enabled:!0,
defer:!1,y:15,borderWidth:1,borderColor:"silver",borderRadius:3,crop:!1,verticalAlign:"top",zIndex:2},dial:{},pivot:{},tooltip:{headerFormat:""},showInLegend:!1});E={type:"gauge",pointClass:v(N,{setState:function(a){this.state=a}}),angular:!0,drawGraph:z,fixedBox:!0,forceDL:!0,trackerGroups:["group","dataLabelsGroup"],translate:function(){var a=this.yAxis,b=this.options,c=a.center;this.generatePoints();x(this.points,function(d){var e=y(b.dial,d.dial),f=F(r(e.radius,80))*c[2]/200,h=F(r(e.baseLength,
70))*f/100,m=F(r(e.rearLength,10))*f/100,g=e.baseWidth||3,l=e.topWidth||1,p=b.overshoot,n=a.startAngleRad+a.translate(d.y,null,null,null,!0);p&&"number"===typeof p?(p=p/180*Math.PI,n=Math.max(a.startAngleRad-p,Math.min(a.endAngleRad+p,n))):!1===b.wrap&&(n=Math.max(a.startAngleRad,Math.min(a.endAngleRad,n)));n=180*n/Math.PI;d.shapeType="path";d.shapeArgs={d:e.path||["M",-m,-g/2,"L",h,-g/2,f,-l/2,f,l/2,h,g/2,-m,g/2,"z"],translateX:c[0],translateY:c[1],rotation:n};d.plotX=c[0];d.plotY=c[1]})},drawPoints:function(){var a=
this,b=a.yAxis.center,c=a.pivot,d=a.options,e=d.pivot,f=a.chart.renderer;x(a.points,function(b){var c=b.graphic,g=b.shapeArgs,e=g.d,p=y(d.dial,b.dial);c?(c.animate(g),g.d=e):b.graphic=f[b.shapeType](g).attr({stroke:p.borderColor||"none","stroke-width":p.borderWidth||0,fill:p.backgroundColor||"black",rotation:g.rotation}).add(a.group)});c?c.animate({translateX:b[0],translateY:b[1]}):a.pivot=f.circle(0,0,r(e.radius,5)).attr({"stroke-width":e.borderWidth||0,stroke:e.borderColor||"silver",fill:e.backgroundColor||
"black"}).translate(b[0],b[1]).add(a.group)},animate:function(a){var b=this;a||(x(b.points,function(a){var d=a.graphic;d&&(d.attr({rotation:180*b.yAxis.startAngleRad/Math.PI}),d.animate({rotation:a.shapeArgs.rotation},b.options.animation))}),b.animate=null)},render:function(){this.group=this.plotGroup("group","series",this.visible?"visible":"hidden",this.options.zIndex,this.chart.seriesGroup);A.prototype.render.call(this);this.group.clip(this.chart.clipRect)},setData:function(a,b){A.prototype.setData.call(this,
a,!1);this.processData();this.generatePoints();r(b,!0)&&this.chart.redraw()},drawTracker:E&&E.drawTrackerPoint};k.gauge=v(k.line,E);t.boxplot=y(t.column,{fillColor:"#FFFFFF",lineWidth:1,medianWidth:2,states:{hover:{brightness:-.3}},threshold:null,tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Maximum: {point.high}<br/>Upper quartile: {point.q3}<br/>Median: {point.median}<br/>Lower quartile: {point.q1}<br/>Minimum: {point.low}<br/>'},whiskerLength:"50%",
whiskerWidth:2});k.boxplot=v(k.column,{type:"boxplot",pointArrayMap:["low","q1","median","q3","high"],toYData:function(a){return[a.low,a.q1,a.median,a.q3,a.high]},pointValKey:"high",pointAttrToOptions:{fill:"fillColor",stroke:"color","stroke-width":"lineWidth"},drawDataLabels:z,translate:function(){var a=this.yAxis,b=this.pointArrayMap;k.column.prototype.translate.apply(this);x(this.points,function(c){x(b,function(b){null!==c[b]&&(c[b+"Plot"]=a.translate(c[b],0,1,0,1))})})},drawPoints:function(){var a=
this,b=a.options,c=a.chart.renderer,d,e,f,h,m,g,l,p,n,k,B,q,O,t,y,w,z,v,A,C,F,E,D=!1!==a.doQuartiles,J,H=a.options.whiskerLength;x(a.points,function(u){n=u.graphic;F=u.shapeArgs;B={};t={};w={};E=u.color||a.color;u.plotY!==K&&(d=u.pointAttr[u.selected?"selected":""],z=F.width,v=G(F.x),A=v+z,C=I(z/2),e=G(D?u.q1Plot:u.lowPlot),f=G(D?u.q3Plot:u.lowPlot),h=G(u.highPlot),m=G(u.lowPlot),B.stroke=u.stemColor||b.stemColor||E,B["stroke-width"]=r(u.stemWidth,b.stemWidth,b.lineWidth),B.dashstyle=u.stemDashStyle||
b.stemDashStyle,t.stroke=u.whiskerColor||b.whiskerColor||E,t["stroke-width"]=r(u.whiskerWidth,b.whiskerWidth,b.lineWidth),w.stroke=u.medianColor||b.medianColor||E,w["stroke-width"]=r(u.medianWidth,b.medianWidth,b.lineWidth),l=B["stroke-width"]%2/2,p=v+C+l,k=["M",p,f,"L",p,h,"M",p,e,"L",p,m],D&&(l=d["stroke-width"]%2/2,p=G(p)+l,e=G(e)+l,f=G(f)+l,v+=l,A+=l,q=["M",v,f,"L",v,e,"L",A,e,"L",A,f,"L",v,f,"z"]),H&&(l=t["stroke-width"]%2/2,h+=l,m+=l,J=/%$/.test(H)?C*parseFloat(H)/100:H/2,O=["M",p-J,h,"L",p+
J,h,"M",p-J,m,"L",p+J,m]),l=w["stroke-width"]%2/2,g=I(u.medianPlot)+l,y=["M",v,g,"L",A,g],n?(u.stem.animate({d:k}),H&&u.whiskers.animate({d:O}),D&&u.box.animate({d:q}),u.medianShape.animate({d:y})):(u.graphic=n=c.g().add(a.group),u.stem=c.path(k).attr(B).add(n),H&&(u.whiskers=c.path(O).attr(t).add(n)),D&&(u.box=c.path(q).attr(d).add(n)),u.medianShape=c.path(y).attr(w).add(n)))})},setStackedPoints:z});t.errorbar=y(t.boxplot,{color:"#000000",grouping:!1,linkedTo:":previous",tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.low}</b> - <b>{point.high}</b><br/>'},
whiskerWidth:null});k.errorbar=v(k.boxplot,{type:"errorbar",pointArrayMap:["low","high"],toYData:function(a){return[a.low,a.high]},pointValKey:"high",doQuartiles:!1,drawDataLabels:k.arearange?k.arearange.prototype.drawDataLabels:z,getColumnMetrics:function(){return this.linkedParent&&this.linkedParent.columnMetrics||k.column.prototype.getColumnMetrics.call(this)}});t.waterfall=y(t.column,{lineWidth:1,lineColor:"#333",dashStyle:"dot",borderColor:"#333",dataLabels:{inside:!0},states:{hover:{lineWidthPlus:0}}});
k.waterfall=v(k.column,{type:"waterfall",upColorProp:"fill",pointValKey:"y",translate:function(){var a=this.options,b=this.yAxis,c,d,e,f,h,m,g,l,p,n=a.threshold,ba=a.stacking;k.column.prototype.translate.apply(this);g=l=n;d=this.points;c=0;for(a=d.length;c<a;c++)e=d[c],m=this.processedYData[c],f=e.shapeArgs,p=(h=ba&&b.stacks[(this.negStacks&&m<n?"-":"")+this.stackKey])?h[e.x].points[this.index+","+c]:[0,m],e.isSum?e.y=m:e.isIntermediateSum&&(e.y=m-l),h=S(g,g+e.y)+p[0],f.y=b.translate(h,0,1),e.isSum?
(f.y=b.translate(p[1],0,1),f.height=Math.min(b.translate(p[0],0,1),b.len)-f.y):e.isIntermediateSum?(f.y=b.translate(p[1],0,1),f.height=Math.min(b.translate(l,0,1),b.len)-f.y,l=p[1]):(0!==g&&(f.height=0<m?b.translate(g,0,1)-f.y:b.translate(g,0,1)-b.translate(g-m,0,1)),g+=m),0>f.height&&(f.y+=f.height,f.height*=-1),e.plotY=f.y=I(f.y)-this.borderWidth%2/2,f.height=S(I(f.height),.001),e.yBottom=f.y+f.height,f=e.plotY+(e.negative?f.height:0),this.chart.inverted?e.tooltipPos[0]=b.len-f:e.tooltipPos[1]=
f},processData:function(a){var b=this.yData,c=this.options.data,d,e=b.length,f,h,m,g,l,p;h=f=m=g=this.options.threshold||0;for(p=0;p<e;p++)l=b[p],d=c&&c[p]?c[p]:{},"sum"===l||d.isSum?b[p]=h:"intermediateSum"===l||d.isIntermediateSum?b[p]=f:(h+=l,f+=l),m=Math.min(h,m),g=Math.max(h,g);A.prototype.processData.call(this,a);this.dataMin=m;this.dataMax=g},toYData:function(a){return a.isSum?0===a.x?null:"sum":a.isIntermediateSum?0===a.x?null:"intermediateSum":a.y},getAttribs:function(){k.column.prototype.getAttribs.apply(this,
arguments);var a=this,b=a.options,c=b.states,d=b.upColor||a.color,b=q.Color(d).brighten(.1).get(),e=y(a.pointAttr),f=a.upColorProp;e[""][f]=d;e.hover[f]=c.hover.upColor||b;e.select[f]=c.select.upColor||d;x(a.points,function(f){f.options.color||(0<f.y?(f.pointAttr=e,f.color=d):f.pointAttr=a.pointAttr)})},getGraphPath:function(){var a=this.data,b=a.length,c=I(this.options.lineWidth+this.borderWidth)%2/2,d=[],e,f,h;for(h=1;h<b;h++)f=a[h].shapeArgs,e=a[h-1].shapeArgs,f=["M",e.x+e.width,e.y+c,"L",f.x,
e.y+c],0>a[h-1].y&&(f[2]+=e.height,f[5]+=e.height),d=d.concat(f);return d},getExtremes:z,drawGraph:A.prototype.drawGraph});t.polygon=y(t.scatter,{marker:{enabled:!1}});k.polygon=v(k.scatter,{type:"polygon",fillGraph:!0,getSegmentPath:function(a){return A.prototype.getSegmentPath.call(this,a).concat("z")},drawGraph:A.prototype.drawGraph,drawLegendSymbol:q.LegendSymbolMixin.drawRectangle});t.bubble=y(t.scatter,{dataLabels:{formatter:function(){return this.point.z},inside:!0,verticalAlign:"middle"},
marker:{lineColor:null,lineWidth:1},minSize:8,maxSize:"20%",softThreshold:!1,states:{hover:{halo:{size:5}}},tooltip:{pointFormat:"({point.x}, {point.y}), Size: {point.z}"},turboThreshold:0,zThreshold:0,zoneAxis:"z"});E=v(N,{haloPath:function(){return N.prototype.haloPath.call(this,this.shapeArgs.r+this.series.options.states.hover.halo.size)},ttBelow:!1});k.bubble=v(k.scatter,{type:"bubble",pointClass:E,pointArrayMap:["y","z"],parallelArrays:["x","y","z"],trackerGroups:["group","dataLabelsGroup"],
bubblePadding:!0,zoneAxis:"z",pointAttrToOptions:{stroke:"lineColor","stroke-width":"lineWidth",fill:"fillColor"},applyOpacity:function(a){var b=this.options.marker,c=r(b.fillOpacity,.5);a=a||b.fillColor||this.color;1!==c&&(a=Z(a).setOpacity(c).get("rgba"));return a},convertAttribs:function(){var a=A.prototype.convertAttribs.apply(this,arguments);a.fill=this.applyOpacity(a.fill);return a},getRadii:function(a,b,c,d){var e,f,h,m=this.zData,g=[],l=this.options,p="width"!==l.sizeBy,n=l.zThreshold,k=b-
a;f=0;for(e=m.length;f<e;f++)h=m[f],l.sizeByAbsoluteValue&&(h=Math.abs(h-n),b=Math.max(b-n,Math.abs(a-n)),a=0),null===h?h=null:h<a?h=c/2-1:(h=0<k?(h-a)/k:.5,p&&0<=h&&(h=Math.sqrt(h)),h=C.ceil(c+h*(d-c))/2),g.push(h);this.radii=g},animate:function(a){var b=this.options.animation;a||(x(this.points,function(a){var d=a.graphic;a=a.shapeArgs;d&&a&&(d.attr("r",1),d.animate({r:a.r},b))}),this.animate=null)},translate:function(){var a,b=this.data,c,d,e=this.radii;k.scatter.prototype.translate.call(this);
for(a=b.length;a--;)c=b[a],d=e?e[a]:0,"number"===typeof d&&d>=this.minPxSize/2?(c.shapeType="circle",c.shapeArgs={x:c.plotX,y:c.plotY,r:d},c.dlBox={x:c.plotX-d,y:c.plotY-d,width:2*d,height:2*d}):c.shapeArgs=c.plotY=c.dlBox=K},drawLegendSymbol:function(a,b){var c=F(a.itemStyle.fontSize)/2;b.legendSymbol=this.chart.renderer.circle(c,a.baseline-c,c).attr({zIndex:3}).add(b.legendGroup);b.legendSymbol.isMarker=!0},drawPoints:k.column.prototype.drawPoints,alignDataLabel:k.column.prototype.alignDataLabel,
buildKDTree:z,applyZones:z});R.prototype.beforePadding=function(){var a=this,b=this.len,c=this.chart,d=0,e=b,f=this.isXAxis,h=f?"xData":"yData",m=this.min,g={},l=C.min(c.plotWidth,c.plotHeight),p=Number.MAX_VALUE,n=-Number.MAX_VALUE,k=this.max-m,B=b/k,q=[];x(this.series,function(b){var h=b.options;!b.bubblePadding||!b.visible&&c.options.chart.ignoreHiddenSeries||(a.allowZoomOutside=!0,q.push(b),f&&(x(["minSize","maxSize"],function(a){var f=h[a],b=/%$/.test(f),f=F(f);g[a]=b?l*f/100:f}),b.minPxSize=
g.minSize,b.maxPxSize=g.maxSize,b=b.zData,b.length&&(p=r(h.zMin,C.min(p,C.max(U(b),!1===h.displayNegative?h.zThreshold:-Number.MAX_VALUE))),n=r(h.zMax,C.max(n,V(b))))))});x(q,function(a){var b=a[h],c=b.length,g;f&&a.getRadii(p,n,a.minPxSize,a.maxPxSize);if(0<k)for(;c--;)"number"===typeof b[c]&&(g=a.radii[c],d=Math.min((b[c]-m)*B-g,d),e=Math.max((b[c]-m)*B+g,e))});q.length&&0<k&&!this.isLog&&(e-=b,B*=(b+d-e)/b,x([["min","userMin",d],["max","userMax",e]],function(b){r(a.options[b[0]],a[b[1]])===K&&
(a[b[0]]+=b[2]/B)}))};(function(){function a(a,b,c){a.call(this,b,c);this.chart.polar&&(this.closeSegment=function(a){var b=this.xAxis.center;a.push("L",b[0],b[1])},this.closedStacks=!0)}function b(a,b){var c=this.chart,g=this.options.animation,d=this.group,e=this.markerGroup,n=this.xAxis.center,k=c.plotLeft,q=c.plotTop;c.polar?c.renderer.isSVG&&(!0===g&&(g={}),b?(c={translateX:n[0]+k,translateY:n[1]+q,scaleX:.001,scaleY:.001},d.attr(c),e&&e.attr(c)):(c={translateX:k,translateY:q,scaleX:1,scaleY:1},
d.animate(c,g),e&&e.animate(c,g),this.animate=null)):a.call(this,b)}var c=A.prototype,d=X.prototype,e;c.searchPointByAngle=function(a){var b=this.chart,c=this.xAxis.pane.center;return this.searchKDTree({clientX:180+-180/Math.PI*Math.atan2(a.chartX-c[0]-b.plotLeft,a.chartY-c[1]-b.plotTop)})};w(c,"buildKDTree",function(a){this.chart.polar&&(this.kdByAngle?this.searchPoint=this.searchPointByAngle:this.kdDimensions=2);a.apply(this)});c.toXY=function(a){var b,c=this.chart,g=a.plotX;b=a.plotY;a.rectPlotX=
g;a.rectPlotY=b;b=this.xAxis.postTranslate(a.plotX,this.yAxis.len-b);a.plotX=a.polarPlotX=b.x-c.plotLeft;a.plotY=a.polarPlotY=b.y-c.plotTop;this.kdByAngle?(c=(g/Math.PI*180+this.xAxis.pane.options.startAngle)%360,0>c&&(c+=360),a.clientX=c):a.clientX=a.plotX};k.area&&w(k.area.prototype,"init",a);k.areaspline&&w(k.areaspline.prototype,"init",a);k.spline&&w(k.spline.prototype,"getPointSpline",function(a,b,c,g){var d,e,n,k,q,t,r;this.chart.polar?(d=c.plotX,e=c.plotY,a=b[g-1],n=b[g+1],this.connectEnds&&
(a||(a=b[b.length-2]),n||(n=b[1])),a&&n&&(k=a.plotX,q=a.plotY,b=n.plotX,t=n.plotY,k=(1.5*d+k)/2.5,q=(1.5*e+q)/2.5,n=(1.5*d+b)/2.5,r=(1.5*e+t)/2.5,b=Math.sqrt(Math.pow(k-d,2)+Math.pow(q-e,2)),t=Math.sqrt(Math.pow(n-d,2)+Math.pow(r-e,2)),k=Math.atan2(q-e,k-d),q=Math.atan2(r-e,n-d),r=Math.PI/2+(k+q)/2,Math.abs(k-r)>Math.PI/2&&(r-=Math.PI),k=d+Math.cos(r)*b,q=e+Math.sin(r)*b,n=d+Math.cos(Math.PI+r)*t,r=e+Math.sin(Math.PI+r)*t,c.rightContX=n,c.rightContY=r),g?(c=["C",a.rightContX||a.plotX,a.rightContY||
a.plotY,k||d,q||e,d,e],a.rightContX=a.rightContY=null):c=["M",d,e]):c=a.call(this,b,c,g);return c});w(c,"translate",function(a){var b=this.chart;a.call(this);if(b.polar&&(this.kdByAngle=b.tooltip&&b.tooltip.shared,!this.preventPostTranslate))for(a=this.points,b=a.length;b--;)this.toXY(a[b])});w(c,"getSegmentPath",function(a,b){var c=this.points;this.chart.polar&&!1!==this.options.connectEnds&&b[b.length-1]===c[c.length-1]&&null!==c[0].y&&(this.connectEnds=!0,b=[].concat(b,[c[0]]));return a.call(this,
b)});w(c,"animate",b);k.column&&(e=k.column.prototype,w(e,"animate",b),w(e,"translate",function(a){var b=this.xAxis,c=this.yAxis.len,d=b.center,e=b.startAngleRad,k=this.chart.renderer,n,q;this.preventPostTranslate=!0;a.call(this);if(b.isRadial)for(b=this.points,q=b.length;q--;)n=b[q],a=n.barX+e,n.shapeType="path",n.shapeArgs={d:k.symbols.arc(d[0],d[1],c-n.plotY,null,{start:a,end:a+n.pointWidth,innerR:c-r(n.yBottom,c)})},this.toXY(n),n.tooltipPos=[n.plotX,n.plotY],n.ttBelow=n.plotY>d[1]}),w(e,"alignDataLabel",
function(a,b,d,e,l,k){this.chart.polar?(a=b.rectPlotX/Math.PI*180,null===e.align&&(e.align=20<a&&160>a?"left":200<a&&340>a?"right":"center"),null===e.verticalAlign&&(e.verticalAlign=45>a||315<a?"bottom":135<a&&225>a?"top":"middle"),c.alignDataLabel.call(this,b,d,e,l,k)):a.call(this,b,d,e,l,k)}));w(d,"getCoordinates",function(a,b){var c=this.chart,d={xAxis:[],yAxis:[]};c.polar?x(c.axes,function(a){var f=a.isXAxis,e=a.center,k=b.chartX-e[0]-c.plotLeft,e=b.chartY-e[1]-c.plotTop;d[f?"xAxis":"yAxis"].push({axis:a,
value:a.translate(f?Math.PI-Math.atan2(k,e):Math.sqrt(Math.pow(k,2)+Math.pow(e,2)),!0)})}):d=a.call(this,b);return d})})()})(Highcharts);
